api_key: 'AIzaSyByyWAUeaOl_39tK3tXM8hfsz4KLfR8a3Y'
cse_id: '72e62b8642f194f09'
gemini_api_key: 'AIzaSyDjH4Hi69XwnhQhzye2PnpyBCqcD90-gd8'  # Add your Gemini API key here
blocked_domains:
  - 'reddit.com'
  - 'instagram.com'
  - 'wikipedia.org'
  - 'linkedin.com'
  - 'youtube.com'
  - 'vexforum.com'
  - 'nytimes.com'
  - 'x.com'
proxies: []
output_file: "output.json"
