//MAIN FILE

import "./globals.css";
import Providers from '../components/Auth/Providers'; 
import { Inter, Poppins } from "next/font/google";
import { AuthProvider } from '../context/AuthContext'; 
import 'react-toastify/dist/ReactToastify.css';
//import Header from '../components/Auth/Header'; // Import Header
import { ToastContainer } from 'react-toastify';


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Info Morph",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.variable} antialiased`}>
        <AuthProvider>
          <Providers>
              
              {children}
              <ToastContainer 
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
            </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
